name: generate animation

on:
  # Menjalankan workflow secara otomatis setiap 24 jam
  schedule:
    - cron: "0 */24 * * *"  # Menjalankan setiap 24 jam sekali
  
  # Memungkinkan untuk menjalankan workflow secara manual
  workflow_dispatch:
  
  # Menjalankan workflow pada setiap push ke branch master (atau main)
  push:
    branches:
      - main  # Ganti dengan "main" jika menggunakan branch main

jobs:
  generate:
    permissions:
      contents: write  # Memberikan izin untuk menulis ke repositori
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Membatasi waktu eksekusi workflow menjadi 5 menit
    
    steps:
      # Langkah pertama: menghasilkan gambar snake dari grafik kontribusi GitHub pengguna
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Menggunakan username repositori pemilik
          outputs: |
            dist/github-contribution-grid-snake.svg  # Output SVG untuk animasi kontribusi
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  # Output SVG dengan tema gelap
        
      # Langkah kedua: push file hasil generate ke branch output
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Menggunakan branch "output" untuk GitHub Pages
          build_dir: dist  # Folder yang berisi file hasil generate
        env:
          GITHUB_TOKEN: ${{ secrets.token }}  # Menggunakan token GitHub yang disimpan di GitHub Secrets
